### ISSUE TITLE
大佬你好，请教一下生成initrd.img的方法

### ISSUE THREAD

**Issue by laoyur** [unifreq/linux-5.4.y#2]
我现在在ubuntu x86上编译完内核后，不知道如何生成initrd.img

我查了很多资料，说是必须在目标机器（我是斐讯N1）上来生成initrd.img
所以我必须先在N1上安装一个armbian，再将modules拷贝到N1上，然后再通过`update-initramfs`或者`mkinitramfs`生成initrd.img，然后再用`mkimage`制作uInitrd？

请问我的理解对不对？希望大佬能指点一二，谢谢！

**Comment by unifreq** [comment]
用的是armbian里的update-initramfs
----- 原始邮件 -----
发件人：laoyur ***@***.***>
收件人："unifreq/linux-5.4.y" ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[unifreq/linux-5.4.y]_大佬你好，请教一下生成initrd.img的方法_(#2)
日期：2021年08月06日 14点16分


我现在在ubuntu x86上编译完内核后，不知道如何生成initrd.img
我查了很多资料，说是必须在目标机器（我是斐讯N1）上来生成initrd.img

所以我必须先在N1上安装一个armbian，再将modules拷贝到N1上，然后再通过update-initramfs或者mkinitramfs生成initrd.img，然后再用mkimage制作uInitrd？
请问我的理解对不对？希望大佬能指点一二，谢谢！

&mdash;
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by laoyur** [comment]
感谢，有空试一下
我是给内核加了sim7600 4G模块的支持，后来发现initrd貌似没必要更新，我直接沿用了你的uInitrd，貌似也行
